#! /bin/sh

sxhkd &
exec setxkbmap -layout us,ru -option grp:lalt_lshift_toggle &
exec ~/lemonconf.sh | lemonbar -b -f 'Perfect DOS VGA 437' &
exec feh --no-xinerama --bg-center ~/Config/dust.jpg &
#colors: tty1 font color: ADADAD, eroute-green: 798b00

bspc config bottom_padding       16
bspc config border_width         2
bspc config window_gap           5
bspc config normal_border_color  "#2b1a0a" 
#2b1a0a 583718 7c4b20
bspc config focused_border_color "#7c4b20"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
